### PR TITLE
Allow editable resource group

### PR DESCRIPTION
**Pull request by patpicos**
Changed property for the resource group field to allow the user to edit. This then allows the use of variable driven values such as $(resourcegroup)

### CODE REVIEW

**Comment by patpicos** [comment]
Hi Maik, any update on this pull request? (i cant seem to add a reviewer)

**Comment by maikvandergaag** [comment]
Hi Patrick,

I haven't had time yet to look into it. I hope to have time tomorrow, or else it will be Thursday.

Sorry I'm really busy at the moment.

With regards,

Maik van der Gaag

On Oct 1, 2018 20:48, Patrick Picard <notifications@github.com> wrote:

Hi Maik, any update on this pull request? (i cant seem to add a reviewer)

**Comment by patpicos** [comment]
Thanks Maik

Im currently working on plan B (to deploy a vsix to my subscription w/ the changes…not knowing whether I need to make more changes to make it work).

I have disabled the RBAC steps in my pipeline and will run them after the first successful ARM deploy.

**Comment by patpicos** [comment]
not bad for a first timer ;) got to learn abit about the extension structure

**Comment by patpicos** [comment]
Hi Maik

Do we need to do anything to see the newer version in our Azure DevOps?

I just added the RBAC task and the RG field is still fully a drop down w/o text override possible

image

**Comment by patpicos** [comment]
It works now! Thanks again

**Pull request merged**
